---
title: Dupliceer een sprite
hero_image: images/banner.png
description: Dupliceer een sprite inclusief de code, uiterlijken en geluiden in Scratch3
version: 4
listed: false
copyedit: false
last_tested: "2021-03-03"
steps:
  - 
    title: Dupliceer een sprite

