---
title: Dupliceer een sprite
hero_image: images/banner.png
description: Duplicate a sprite including its code, costumes, and sounds in Scratch 3
version: 4
listed: false
copyedit: false
last_tested: "2021-03-03"
steps:
  - 
    title: Dupliceer een sprite

