---
title: एक स्प्राइटची नक्कल करा
hero_image: प्रतिमा / banner.png
description: स्क्रॅच 3 मध्ये त्याचा कोड, पोशाख आणि आवाजांसह स्प्राइटची नक्कल करा
version: 0
listed: false
copyedit: false
last_tested: "2021-03-03"
steps:
  - 
    title: एक स्प्राइटची नक्कल करा

