---
title: एक स्प्राइट को डुप्लिकेट करें
hero_image: images/banner.png
description: स्क्रैच 3 में स्प्राइट के कोड, वेशभूषा और ध्वनियों सहित स्प्राइट को डुप्लिकेट करें
version: 4
listed: false
copyedit: false
last_tested: "2021-03-03"
steps:
  - 
    title: एक स्प्राइट को डुप्लिकेट करें

