---
title: Phinda kabini isprite
hero_image: images/banner.png
description: Phinda kabini isprite nekhowudi yaso, kunye neempahla, neezandi zaso kuScratch 3
version: 4
listed: false
copyedit: false
last_tested: "2021-03-03"
steps:
  - title: Phinda kabini isprite

