---
title: Dupliciraj lika
hero_image: images/banner.png
description: Dupliciraj lika uključujući njegov kôd, kostime i zvukove u Scratch-u 3
version: 4
listed: false
copyedit: false
last_tested: "2021-03-03"
steps:
  - title: Dupliciraj lika

