---
title: Dyblygu corlun
hero_image: images/banner.png
description: Dyblygu corlun gan gynnwys ei god, ei wisgoedd, a'i synau yn Scratch 3
version: 4
listed: false
copyedit: false
last_tested: "2021-03-03"
steps:
  - 
    title: Dyblygu corlun

