---
title: Eine Figur duplizieren (kopieren)
hero_image: images/banner.png
description: Dupliziere (kopiere) eine Figur mit Skripten, Kostümen und Klänge in Scratch 3
version: 4
listed: false
copyedit: false
last_tested: "2021-03-03"
steps:
  - title: Eine Figur duplizieren

