---
title: Duplique um ator
hero_image: images/banner.png
description: Duplique um ator incluindo seu código, fantasias e sons no Scratch 3
version: 4
listed: false
copyedit: false
last_tested: "2021-03-03"
steps:
  - 
    title: Duplique um ator

