---
title: Duplikuj postavu
hero_image: images/banner.png
description: Duplikujte postavu včetně jeho kódu, kostýmů a zvuků ve Scratch 3
version: 4
listed: false
copyedit: false
last_tested: "2021-03-03"
steps:
  - 
    title: Duplikuj postavu

