---
title: Duplica un objeto
hero_image: images/banner.png
description: Duplica un objeto, incluido su código, disfraces y sonidos en Scratch 3
version: 4
listed: false
copyedit: false
last_tested: "2021-03-03"
steps:
  - title: Duplica un objeto

