---
title: Zduplikuj duszka
hero_image: images / banner.png
description: Zduplikuj duszka, w tym jego kod, kostiumy i dźwięki w Scratch 3
version: 4
listed: false
copyedit: false
last_tested: "2021-03-03"
steps:
  - 
    title: Zduplikuj duszka

