---
title: Duplicera en sprajt
hero_image: images/banner.png
description: Duplicera en sprajt med dess kod, klädslar och ljud i Scratch 3
version: 4
listed: false
copyedit: false
last_tested: "2021-03-03"
steps:
  - title: Duplicera en sprajt

