---
title: Αντιγράψτε ένα μπλοκ γραφικών
hero_image: images/banner.png
description: Αντιγράψτε ένα μπλοκ γραφικών που περιλαμβάνει τον κωδικό, τα κοστούμια και τους ήχους του στο Scratch 3
version: 4
listed: false
copyedit: false
last_tested: "2021-03-03"
steps:
  - title: Αντιγράψτε ένα μπλοκ γραφικών

